(generic) ubuntu@192.168.5.237 ~/rubin $ pixi run test
✨ Pixi task (test in dev): python -m pytest tests/ -v --tb=short
========================================================================================================================================================================= test session starts ==========================================================================================================================================================================
platform linux -- Python 3.12.13, pytest-9.0.3, pluggy-1.6.0 -- /mnt/rubin/.pixi/envs/dev/bin/python
cachedir: .pytest_cache
rootdir: /mnt/rubin
configfile: pyproject.toml
plugins: anyio-4.13.0, cov-7.1.0
collected 142 items                                                                                                                                                                                                                                                                                                                                                    

tests/test_data_utils.py::TestReduceMemUsage::test_no_float16 PASSED                                                                                                                                                                                                                                                                                             [  0%]
tests/test_data_utils.py::TestReduceMemUsage::test_integer_downcast PASSED                                                                                                                                                                                                                                                                                       [  1%]
tests/test_data_utils.py::TestReduceMemUsage::test_float_at_least_float32 PASSED                                                                                                                                                                                                                                                                                 [  2%]
tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_removes_correlated_pair FAILED                                                                                                                                                                                                                                                         [  2%]
tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_absorbed_by_mapping FAILED                                                                                                                                                                                                                                                             [  3%]
tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_keeps_uncorrelated FAILED                                                                                                                                                                                                                                                              [  4%]
tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_high_threshold_removes_nothing FAILED                                                                                                                                                                                                                                                  [  4%]
tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_single_column FAILED                                                                                                                                                                                                                                                                   [  5%]
tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_without_importances FAILED                                                                                                                                                                                                                                                             [  6%]
tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_categorical_columns_skipped FAILED                                                                                                                                                                                                                                                     [  7%]
tests/test_feature_selection.py::TestSelectFeaturesByImportance::test_single_method PASSED                                                                                                                                                                                                                                                                       [  7%]
tests/test_feature_selection.py::TestSelectFeaturesByImportance::test_union_of_two_methods PASSED                                                                                                                                                                                                                                                                [  8%]
tests/test_feature_selection.py::TestSelectFeaturesByImportance::test_max_features_caps_union PASSED                                                                                                                                                                                                                                                             [  9%]
tests/test_feature_selection.py::TestSelectFeaturesByImportance::test_empty_importances PASSED                                                                                                                                                                                                                                                                   [  9%]
tests/test_feature_selection.py::TestSelectFeaturesByImportance::test_preserves_column_order PASSED                                                                                                                                                                                                                                                              [ 10%]
tests/test_model_registry.py::TestModelRegistry::test_default_registry_contains_all_models PASSED                                                                                                                                                                                                                                                                [ 11%]
tests/test_model_registry.py::TestModelRegistry::test_unknown_model_raises PASSED                                                                                                                                                                                                                                                                                [ 11%]
tests/test_model_registry.py::TestModelRegistry::test_create_slearner PASSED                                                                                                                                                                                                                                                                                     [ 12%]
tests/test_model_registry.py::TestModelRegistry::test_create_nonparamdml_has_discrete_flags PASSED                                                                                                                                                                                                                                                               [ 13%]
tests/test_model_registry.py::TestModelRegistry::test_create_drlearner_has_cv_and_random_state FAILED                                                                                                                                                                                                                                                            [ 14%]
tests/test_model_registry.py::TestModelRegistry::test_create_drlearner_has_discrete_outcome PASSED                                                                                                                                                                                                                                                               [ 14%]
tests/test_model_registry.py::TestModelRegistry::test_create_causalforestdml_has_discrete_flags PASSED                                                                                                                                                                                                                                                           [ 15%]
tests/test_model_registry.py::TestChooseChampion::test_highest_metric PASSED                                                                                                                                                                                                                                                                                     [ 16%]
tests/test_model_registry.py::TestChooseChampion::test_lowest_metric PASSED                                                                                                                                                                                                                                                                                      [ 16%]
tests/test_model_registry.py::TestChooseChampion::test_missing_metric_ignored PASSED                                                                                                                                                                                                                                                                             [ 17%]
tests/test_model_registry.py::TestChooseChampion::test_empty_list_returns_none PASSED                                                                                                                                                                                                                                                                            [ 18%]
tests/test_model_registry.py::TestPredictEffect::test_prefers_const_marginal_effect PASSED                                                                                                                                                                                                                                                                       [ 19%]
tests/test_model_registry.py::TestPredictEffect::test_falls_back_to_effect PASSED                                                                                                                                                                                                                                                                                [ 19%]
tests/test_model_registry.py::TestPredictEffect::test_raises_without_either PASSED                                                                                                                                                                                                                                                                               [ 20%]
tests/test_preprocessing.py::TestFitPreprocessor::test_roundtrip PASSED                                                                                                                                                                                                                                                                                          [ 21%]
tests/test_preprocessing.py::TestFitPreprocessor::test_unknown_category_gets_minus_one PASSED                                                                                                                                                                                                                                                                    [ 21%]
tests/test_preprocessing.py::TestFitPreprocessor::test_missing_column_filled_with_nan PASSED                                                                                                                                                                                                                                                                     [ 22%]
tests/test_preprocessing.py::TestFitPreprocessor::test_fill_na_mean PASSED                                                                                                                                                                                                                                                                                       [ 23%]
tests/test_preprocessing.py::TestFitPreprocessor::test_fill_na_zero PASSED                                                                                                                                                                                                                                                                                       [ 23%]
tests/test_preprocessing.py::TestFitPreprocessor::test_fill_na_mode PASSED                                                                                                                                                                                                                                                                                       [ 24%]
tests/test_preprocessing.py::TestFitPreprocessor::test_fill_na_max PASSED                                                                                                                                                                                                                                                                                        [ 25%]
tests/test_preprocessing.py::TestFitPreprocessor::test_fill_na_none PASSED                                                                                                                                                                                                                                                                                       [ 26%]
tests/test_preprocessing.py::TestSimpleCSVPreprocessor::test_build_and_transform PASSED                                                                                                                                                                                                                                                                          [ 26%]
tests/test_preprocessing.py::TestSimpleCSVPreprocessor::test_schema_validation PASSED                                                                                                                                                                                                                                                                            [ 27%]
tests/test_preprocessing.py::TestSimpleCSVPreprocessor::test_schema_missing_column PASSED                                                                                                                                                                                                                                                                        [ 28%]
tests/test_schema_utils.py::TestSchema::test_from_dataframe PASSED                                                                                                                                                                                                                                                                                               [ 28%]
tests/test_schema_utils.py::TestSchema::test_save_and_load PASSED                                                                                                                                                                                                                                                                                                [ 29%]
tests/test_schema_utils.py::TestSchema::test_validate_ok PASSED                                                                                                                                                                                                                                                                                                  [ 30%]
tests/test_schema_utils.py::TestSchema::test_validate_missing_column PASSED                                                                                                                                                                                                                                                                                      [ 30%]
tests/test_schema_utils.py::TestSchema::test_validate_extra_columns_ok_non_strict PASSED                                                                                                                                                                                                                                                                         [ 31%]
tests/test_schema_utils.py::TestSchema::test_validate_extra_columns_fail_strict PASSED                                                                                                                                                                                                                                                                           [ 32%]
tests/test_settings.py::TestLoadConfig::test_minimal_config PASSED                                                                                                                                                                                                                                                                                               [ 33%]
tests/test_settings.py::TestLoadConfig::test_seed_alias PASSED                                                                                                                                                                                                                                                                                                   [ 33%]
tests/test_settings.py::TestLoadConfig::test_unknown_model_rejected PASSED                                                                                                                                                                                                                                                                                       [ 34%]
tests/test_settings.py::TestLoadConfig::test_extra_keys_rejected PASSED                                                                                                                                                                                                                                                                                          [ 35%]
tests/test_settings.py::TestLoadConfig::test_manual_champion_must_be_in_models PASSED                                                                                                                                                                                                                                                                            [ 35%]
tests/test_settings.py::TestLoadConfig::test_manual_champion_valid PASSED                                                                                                                                                                                                                                                                                        [ 36%]
tests/test_settings.py::TestLoadConfig::test_all_model_names_supported PASSED                                                                                                                                                                                                                                                                                    [ 37%]
tests/test_settings.py::TestLoadConfig::test_source_config_path_set PASSED                                                                                                                                                                                                                                                                                       [ 38%]
tests/test_settings.py::TestLoadConfig::test_validate_on_external PASSED                                                                                                                                                                                                                                                                                         [ 38%]
tests/test_settings.py::TestLoadConfig::test_validate_on_holdout_rejected PASSED                                                                                                                                                                                                                                                                                 [ 39%]
tests/test_settings.py::TestLoadConfig::test_validate_on_test_rejected PASSED                                                                                                                                                                                                                                                                                    [ 40%]
tests/test_settings.py::TestLoadConfig::test_feature_selection_defaults PASSED                                                                                                                                                                                                                                                                                   [ 40%]
tests/test_settings.py::TestLoadConfig::test_feature_selection_multiple_methods PASSED                                                                                                                                                                                                                                                                           [ 41%]
tests/test_settings.py::TestLoadConfig::test_feature_selection_old_method_field_rejected PASSED                                                                                                                                                                                                                                                                  [ 42%]
tests/test_settings.py::TestLoadConfig::test_feature_selection_old_importance_threshold_rejected PASSED                                                                                                                                                                                                                                                          [ 42%]
tests/test_settings.py::TestLoadConfig::test_surrogate_tree_default_disabled PASSED                                                                                                                                                                                                                                                                              [ 43%]
tests/test_settings.py::TestLoadConfig::test_surrogate_tree_enabled PASSED                                                                                                                                                                                                                                                                                       [ 44%]
tests/test_settings.py::TestLoadConfig::test_data_prep_deduplicate_default PASSED                                                                                                                                                                                                                                                                                [ 45%]
tests/test_settings.py::TestLoadConfig::test_data_prep_deduplicate_enabled PASSED                                                                                                                                                                                                                                                                                [ 45%]
tests/test_settings.py::TestLoadConfig::test_treatment_config_default_binary PASSED                                                                                                                                                                                                                                                                              [ 46%]
tests/test_settings.py::TestLoadConfig::test_treatment_config_multi FAILED                                                                                                                                                                                                                                                                                       [ 47%]
tests/test_settings.py::TestLoadConfig::test_mt_blocks_bt_only_models PASSED                                                                                                                                                                                                                                                                                     [ 47%]
tests/test_settings.py::TestLoadConfig::test_mt_blocks_xlearner PASSED                                                                                                                                                                                                                                                                                           [ 48%]
tests/test_settings.py::TestLoadConfig::test_mt_blocks_tlearner PASSED                                                                                                                                                                                                                                                                                           [ 49%]
tests/test_settings.py::TestLoadConfig::test_mt_allows_dml FAILED                                                                                                                                                                                                                                                                                                [ 50%]
tests/test_settings.py::TestLoadConfig::test_data_prep_target_single_string PASSED                                                                                                                                                                                                                                                                               [ 50%]
tests/test_settings.py::TestLoadConfig::test_data_prep_target_list PASSED                                                                                                                                                                                                                                                                                        [ 51%]
tests/test_settings.py::TestLoadConfig::test_shap_values_defaults PASSED                                                                                                                                                                                                                                                                                         [ 52%]
tests/test_settings.py::TestLoadConfig::test_shap_values_enabled PASSED                                                                                                                                                                                                                                                                                          [ 52%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_no_penalty_when_zero PASSED                                                                                                                                                                                                                                                                                [ 53%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_no_penalty_within_tolerance PASSED                                                                                                                                                                                                                                                                         [ 54%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_penalty_above_tolerance PASSED                                                                                                                                                                                                                                                                             [ 54%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_stronger_penalty_means_worse_score PASSED                                                                                                                                                                                                                                                                  [ 55%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_scale_invariant_log_loss PASSED                                                                                                                                                                                                                                                                            [ 56%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_scale_invariant_r_loss FAILED                                                                                                                                                                                                                                                                              [ 57%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_no_penalty_when_train_worse_than_val PASSED                                                                                                                                                                                                                                                                [ 57%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_penalty_exact_formula PASSED                                                                                                                                                                                                                                                                               [ 58%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_val_score_near_zero PASSED                                                                                                                                                                                                                                                                                 [ 59%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_blt_default_tolerance PASSED                                                                                                                                                                                                                                                                               [ 59%]
tests/test_tuning.py::TestOverfitPenaltyFormula::test_fmt_default_tolerance FAILED                                                                                                                                                                                                                                                                               [ 60%]
tests/test_tuning.py::TestScoreClassifier::test_log_loss_is_negative PASSED                                                                                                                                                                                                                                                                                      [ 61%]
tests/test_tuning.py::TestScoreClassifier::test_better_predictions_give_higher_log_loss PASSED                                                                                                                                                                                                                                                                   [ 61%]
tests/test_tuning.py::TestScoreClassifier::test_single_class_returns_default PASSED                                                                                                                                                                                                                                                                              [ 62%]
tests/test_tuning.py::TestScoreClassifier::test_log_loss_2d_proba PASSED                                                                                                                                                                                                                                                                                         [ 63%]
tests/test_tuning.py::TestScoreRegressor::test_neg_mse_is_negative PASSED                                                                                                                                                                                                                                                                                        [ 64%]
tests/test_tuning.py::TestScoreRegressor::test_better_predictions_give_higher_neg_mse PASSED                                                                                                                                                                                                                                                                     [ 64%]
tests/test_tuning.py::TestScoreRegressor::test_all_metrics_higher_is_better PASSED                                                                                                                                                                                                                                                                               [ 65%]
tests/test_tuning.py::TestCatBoostBootstrapFix::test_classifier_subsample_gets_mvs FAILED                                                                                                                                                                                                                                                                        [ 66%]
tests/test_tuning.py::TestCatBoostBootstrapFix::test_classifier_no_subsample_no_mvs FAILED                                                                                                                                                                                                                                                                       [ 66%]
tests/test_tuning.py::TestCatBoostBootstrapFix::test_classifier_explicit_bootstrap_preserved FAILED                                                                                                                                                                                                                                                              [ 67%]
tests/test_tuning.py::TestCatBoostBootstrapFix::test_regressor_subsample_gets_mvs FAILED                                                                                                                                                                                                                                                                         [ 68%]
tests/test_tuning.py::TestCausalForestAdapterFromFitted::test_sets_all_attributes PASSED                                                                                                                                                                                                                                                                         [ 69%]
tests/test_tuning.py::TestCausalForestAdapterFromFitted::test_effect_delegates_to_cf FAILED                                                                                                                                                                                                                                                                      [ 69%]
tests/test_tuning.py::TestCausalForestAdapterFromFitted::test_feature_importances_delegates PASSED                                                                                                                                                                                                                                                               [ 70%]
tests/test_tuning.py::TestConfigDefaults::test_blt_tolerance_default PASSED                                                                                                                                                                                                                                                                                      [ 71%]
tests/test_tuning.py::TestConfigDefaults::test_fmt_tolerance_default PASSED                                                                                                                                                                                                                                                                                      [ 71%]
tests/test_tuning.py::TestConfigDefaults::test_blt_penalty_default_zero PASSED                                                                                                                                                                                                                                                                                   [ 72%]
tests/test_tuning.py::TestConfigDefaults::test_fmt_penalty_default_zero PASSED                                                                                                                                                                                                                                                                                   [ 73%]
tests/test_tuning.py::TestConfigDefaults::test_tune_models_default_empty PASSED                                                                                                                                                                                                                                                                                  [ 73%]
tests/test_tuning.py::TestConfigDefaults::test_tuning_seed_default PASSED                                                                                                                                                                                                                                                                                        [ 74%]
tests/test_tuning.py::TestConfigDefaults::test_tuning_seed_differs_from_random_seed PASSED                                                                                                                                                                                                                                                                       [ 75%]
tests/test_tuning.py::TestBuildBaseLearner::test_unknown_type_raises PASSED                                                                                                                                                                                                                                                                                      [ 76%]
tests/test_tuning.py::TestBuildBaseLearner::test_unknown_task_raises PASSED                                                                                                                                                                                                                                                                                      [ 76%]
tests/test_tuning.py::TestBuildBaseLearner::test_both_without_learner_type_fallback FAILED                                                                                                                                                                                                                                                                       [ 77%]
tests/test_tuning.py::TestPenaltyPruningInteraction::test_penalty_on_means_not_per_fold PASSED                                                                                                                                                                                                                                                                   [ 78%]
tests/test_tuning.py::TestFinalModelTunerInit::test_fmt_init_warns_on_equal_seeds PASSED                                                                                                                                                                                                                                                                         [ 78%]
tests/test_tuning.py::TestFinalModelTunerInit::test_fmt_init_no_warn_different_seeds PASSED                                                                                                                                                                                                                                                                      [ 79%]
tests/test_tuning.py::TestFinalModelTunerInit::test_fmt_skips_unsupported_models PASSED                                                                                                                                                                                                                                                                          [ 80%]
tests/test_tuning.py::TestFinalModelTunerInit::test_fmt_overfit_penalty_scale_floor PASSED                                                                                                                                                                                                                                                                       [ 80%]
tests/test_tuning.py::TestRCTWarning::test_rct_warning_format_string PASSED                                                                                                                                                                                                                                                                                      [ 81%]
tests/test_uplift_metrics.py::TestUpliftCurve::test_shape PASSED                                                                                                                                                                                                                                                                                                 [ 82%]
tests/test_uplift_metrics.py::TestUpliftCurve::test_binary_check PASSED                                                                                                                                                                                                                                                                                          [ 83%]
tests/test_uplift_metrics.py::TestAuuc::test_positive_for_good_model PASSED                                                                                                                                                                                                                                                                                      [ 83%]
tests/test_uplift_metrics.py::TestAuuc::test_near_zero_for_random PASSED                                                                                                                                                                                                                                                                                         [ 84%]
tests/test_uplift_metrics.py::TestQiniCoefficient::test_positive_for_good_model PASSED                                                                                                                                                                                                                                                                           [ 85%]
tests/test_uplift_metrics.py::TestUpliftAtK::test_uplift_at_10pct PASSED                                                                                                                                                                                                                                                                                         [ 85%]
tests/test_uplift_metrics.py::TestUpliftAtK::test_zero_fraction PASSED                                                                                                                                                                                                                                                                                           [ 86%]
tests/test_uplift_metrics.py::TestPolicyValue::test_binary_check PASSED                                                                                                                                                                                                                                                                                          [ 87%]
tests/test_uplift_metrics.py::TestPolicyValue::test_all_below_threshold FAILED                                                                                                                                                                                                                                                                                   [ 88%]
tests/test_uplift_metrics.py::TestCheckDiscrete::test_valid_discrete PASSED                                                                                                                                                                                                                                                                                      [ 88%]
tests/test_uplift_metrics.py::TestCheckDiscrete::test_non_integer_raises PASSED                                                                                                                                                                                                                                                                                  [ 89%]
tests/test_uplift_metrics.py::TestCheckDiscrete::test_negative_raises PASSED                                                                                                                                                                                                                                                                                     [ 90%]
tests/test_uplift_metrics.py::TestUpliftCurveMtPerArm::test_shape PASSED                                                                                                                                                                                                                                                                                         [ 90%]
tests/test_uplift_metrics.py::TestUpliftCurveMtPerArm::test_two_arms PASSED                                                                                                                                                                                                                                                                                      [ 91%]
tests/test_uplift_metrics.py::TestPolicyValueMt::test_returns_float PASSED                                                                                                                                                                                                                                                                                       [ 92%]
tests/test_uplift_metrics.py::TestPolicyValueMt::test_with_uniform_propensity PASSED                                                                                                                                                                                                                                                                             [ 92%]
tests/test_uplift_metrics.py::TestPolicyValuePerArm::test_returns_float PASSED                                                                                                                                                                                                                                                                                   [ 93%]
tests/test_uplift_metrics.py::TestPolicyValuePerArm::test_all_below_threshold FAILED                                                                                                                                                                                                                                                                             [ 94%]
tests/test_uplift_metrics.py::TestPolicyValuePerArm::test_consistent_with_bt_policy_value PASSED                                                                                                                                                                                                                                                                 [ 95%]
tests/test_uplift_metrics.py::TestPolicyValuePerArm::test_arm2_ignores_arm1 FAILED                                                                                                                                                                                                                                                                               [ 95%]
tests/test_uplift_metrics.py::TestOptimalTreatmentAssignment::test_shape PASSED                                                                                                                                                                                                                                                                                  [ 96%]
tests/test_uplift_metrics.py::TestOptimalTreatmentAssignment::test_values_in_range PASSED                                                                                                                                                                                                                                                                        [ 97%]
tests/test_uplift_metrics.py::TestOptimalTreatmentAssignment::test_negative_effects_yield_control PASSED                                                                                                                                                                                                                                                         [ 97%]
tests/test_uplift_metrics.py::TestMtEvalSummary::test_keys PASSED                                                                                                                                                                                                                                                                                                [ 98%]
tests/test_uplift_metrics.py::TestMtEvalSummary::test_with_propensity PASSED                                                                                                                                                                                                                                                                                     [ 99%]
tests/test_uplift_metrics.py::TestMtEvalSummary::test_distribution_sums_to_one PASSED                                                                                                                                                                                                                                                                            [100%]

=============================================================================================================================================================================== FAILURES ===============================================================================================================================================================================
___________________________________________________________________________________________________________________________________________________ TestRemoveHighlyCorrelatedFeatures.test_removes_correlated_pair ____________________________________________________________________________________________________________________________________________________
tests/test_feature_selection.py:31: in test_removes_correlated_pair
    result, removed, absorbed = remove_highly_correlated_features(
E   TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
_____________________________________________________________________________________________________________________________________________________ TestRemoveHighlyCorrelatedFeatures.test_absorbed_by_mapping ______________________________________________________________________________________________________________________________________________________
tests/test_feature_selection.py:41: in test_absorbed_by_mapping
    _, _, absorbed = remove_highly_correlated_features(
E   TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
______________________________________________________________________________________________________________________________________________________ TestRemoveHighlyCorrelatedFeatures.test_keeps_uncorrelated ______________________________________________________________________________________________________________________________________________________
tests/test_feature_selection.py:49: in test_keeps_uncorrelated
    result, removed, _ = remove_highly_correlated_features(
E   TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
________________________________________________________________________________________________________________________________________________ TestRemoveHighlyCorrelatedFeatures.test_high_threshold_removes_nothing ________________________________________________________________________________________________________________________________________________
tests/test_feature_selection.py:58: in test_high_threshold_removes_nothing
    result, removed, absorbed = remove_highly_correlated_features(
E   TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
________________________________________________________________________________________________________________________________________________________ TestRemoveHighlyCorrelatedFeatures.test_single_column _________________________________________________________________________________________________________________________________________________________
tests/test_feature_selection.py:66: in test_single_column
    result, removed, absorbed = remove_highly_correlated_features(X, threshold=0.9)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
_____________________________________________________________________________________________________________________________________________________ TestRemoveHighlyCorrelatedFeatures.test_without_importances ______________________________________________________________________________________________________________________________________________________
tests/test_feature_selection.py:73: in test_without_importances
    result, removed, absorbed = remove_highly_correlated_features(
E   TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
_________________________________________________________________________________________________________________________________________________ TestRemoveHighlyCorrelatedFeatures.test_categorical_columns_skipped __________________________________________________________________________________________________________________________________________________
tests/test_feature_selection.py:87: in test_categorical_columns_skipped
    result, removed, _ = remove_highly_correlated_features(X, threshold=0.5)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
___________________________________________________________________________________________________________________________________________________ TestModelRegistry.test_create_drlearner_has_cv_and_random_state ____________________________________________________________________________________________________________________________________________________
tests/test_model_registry.py:45: in test_create_drlearner_has_cv_and_random_state
    assert getattr(model, "cv", None) == 5
E   AssertionError: assert StratifiedKFold(n_splits=5, random_state=123, shuffle=True) == 5
E    +  where StratifiedKFold(n_splits=5, random_state=123, shuffle=True) = getattr(<econml.dr._drlearner.DRLearner object at 0x7f597abe3530>, 'cv', None)
______________________________________________________________________________________________________________________________________________________________ TestLoadConfig.test_treatment_config_multi ______________________________________________________________________________________________________________________________________________________________
tests/test_settings.py:208: in test_treatment_config_multi
    cfg = load_config(path)
          ^^^^^^^^^^^^^^^^^
rubin/settings.py:612: in load_config
    return AnalysisConfig.model_validate(raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   pydantic_core._pydantic_core.ValidationError: 1 validation error for AnalysisConfig
E     Value error, treatment.type='multi' mit selection.metric='qini': Diese Metrik existiert bei Multi-Treatment nicht (nur per-Arm-Varianten). Empfohlen: 'policy_value' (global IPW), 'policy_value_T1', 'qini_T1', 'auuc_T1', etc. [type=value_error, input_value={'data_files': {'t_file':...nfig_multi0/config.yml'}, input_type=dict]
E       For further information visit https://errors.pydantic.dev/2.13/v/value_error
__________________________________________________________________________________________________________________________________________________________________ TestLoadConfig.test_mt_allows_dml ___________________________________________________________________________________________________________________________________________________________________
tests/test_settings.py:236: in test_mt_allows_dml
    cfg = load_config(path)
          ^^^^^^^^^^^^^^^^^
rubin/settings.py:612: in load_config
    return AnalysisConfig.model_validate(raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   pydantic_core._pydantic_core.ValidationError: 1 validation error for AnalysisConfig
E     Value error, treatment.type='multi' mit selection.metric='qini': Diese Metrik existiert bei Multi-Treatment nicht (nur per-Arm-Varianten). Empfohlen: 'policy_value' (global IPW), 'policy_value_T1', 'qini_T1', 'auuc_T1', etc. [type=value_error, input_value={'data_files': {'t_file':...allows_dml0/config.yml'}, input_type=dict]
E       For further information visit https://errors.pydantic.dev/2.13/v/value_error
________________________________________________________________________________________________________________________________________________________ TestOverfitPenaltyFormula.test_scale_invariant_r_loss _________________________________________________________________________________________________________________________________________________________
tests/test_tuning.py:164: in test_scale_invariant_r_loss
    assert abs(relative_impact - ll_relative) < 0.001  # identisch
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   assert 0.06000000000000005 < 0.001
E    +  where 0.06000000000000005 = abs((0.0 - -0.06000000000000005))
_________________________________________________________________________________________________________________________________________________________ TestOverfitPenaltyFormula.test_fmt_default_tolerance _________________________________________________________________________________________________________________________________________________________
tests/test_tuning.py:203: in test_fmt_default_tolerance
    assert result < -0.005
E   assert -0.005 < -0.005
_____________________________________________________________________________________________________________________________________________________ TestCatBoostBootstrapFix.test_classifier_subsample_gets_mvs ______________________________________________________________________________________________________________________________________________________
tests/test_tuning.py:283: in test_classifier_subsample_gets_mvs
    tuning_mod._build_catboost_classifier({"subsample": 0.7, "iterations": 10}, seed=42)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: module 'rubin.tuning' has no attribute '_build_catboost_classifier'
_____________________________________________________________________________________________________________________________________________________ TestCatBoostBootstrapFix.test_classifier_no_subsample_no_mvs _____________________________________________________________________________________________________________________________________________________
tests/test_tuning.py:289: in test_classifier_no_subsample_no_mvs
    tuning_mod._build_catboost_classifier({"iterations": 10}, seed=42)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: module 'rubin.tuning' has no attribute '_build_catboost_classifier'
________________________________________________________________________________________________________________________________________________ TestCatBoostBootstrapFix.test_classifier_explicit_bootstrap_preserved _________________________________________________________________________________________________________________________________________________
tests/test_tuning.py:295: in test_classifier_explicit_bootstrap_preserved
    tuning_mod._build_catboost_classifier({"subsample": 0.7, "bootstrap_type": "Bernoulli"}, seed=42)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: module 'rubin.tuning' has no attribute '_build_catboost_classifier'
______________________________________________________________________________________________________________________________________________________ TestCatBoostBootstrapFix.test_regressor_subsample_gets_mvs ______________________________________________________________________________________________________________________________________________________
tests/test_tuning.py:301: in test_regressor_subsample_gets_mvs
    tuning_mod._build_catboost_regressor({"subsample": 0.7, "iterations": 10}, seed=42)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: module 'rubin.tuning' has no attribute '_build_catboost_regressor'
____________________________________________________________________________________________________________________________________________________ TestCausalForestAdapterFromFitted.test_effect_delegates_to_cf _____________________________________________________________________________________________________________________________________________________
tests/test_tuning.py:333: in test_effect_delegates_to_cf
    assert result.shape == (2,)
E   assert (2, 1) == (2,)
E     
E     Left contains one more item: 1
E     
E     Full diff:
E       (
E           2,
E     +     1,
E       )
_____________________________________________________________________________________________________________________________________________________ TestBuildBaseLearner.test_both_without_learner_type_fallback _____________________________________________________________________________________________________________________________________________________
tests/test_tuning.py:391: in test_both_without_learner_type_fallback
    with patch.object(tuning_mod, "_build_catboost_classifier") as mock:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.pixi/envs/dev/lib/python3.12/unittest/mock.py:1467: in __enter__
    original, local = self.get_original()
                      ^^^^^^^^^^^^^^^^^^^
.pixi/envs/dev/lib/python3.12/unittest/mock.py:1437: in get_original
    raise AttributeError(
E   AttributeError: <module 'rubin.tuning' from '/mnt/rubin/rubin/tuning/__init__.py'> does not have the attribute '_build_catboost_classifier'
_______________________________________________________________________________________________________________________________________________________________ TestPolicyValue.test_all_below_threshold _______________________________________________________________________________________________________________________________________________________________
tests/test_uplift_metrics.py:117: in test_all_below_threshold
    assert val == 0.0
E   assert -0.005684204631366708 == 0.0
____________________________________________________________________________________________________________________________________________________________ TestPolicyValuePerArm.test_all_below_threshold ____________________________________________________________________________________________________________________________________________________________
tests/test_uplift_metrics.py:175: in test_all_below_threshold
    assert pv == 0.0
E   assert -0.25 == 0.0
_____________________________________________________________________________________________________________________________________________________________ TestPolicyValuePerArm.test_arm2_ignores_arm1 _____________________________________________________________________________________________________________________________________________________________
tests/test_uplift_metrics.py:203: in test_arm2_ignores_arm1
    assert pv == pytest.approx(expected, abs=1e-10)
E   assert -0.02886726193670923 == -0.16774541531823087 ± 1.0e-10
E     
E     comparison failed
E     Obtained: -0.02886726193670923
E     Expected: -0.16774541531823087 ± 1.0e-10
======================================================================================================================================================================= short test summary info ========================================================================================================================================================================
FAILED tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_removes_correlated_pair - TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
FAILED tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_absorbed_by_mapping - TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
FAILED tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_keeps_uncorrelated - TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
FAILED tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_high_threshold_removes_nothing - TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
FAILED tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_single_column - TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
FAILED tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_without_importances - TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
FAILED tests/test_feature_selection.py::TestRemoveHighlyCorrelatedFeatures::test_categorical_columns_skipped - TypeError: remove_highly_correlated_features() got an unexpected keyword argument 'threshold'
FAILED tests/test_model_registry.py::TestModelRegistry::test_create_drlearner_has_cv_and_random_state - AssertionError: assert StratifiedKFold(n_splits=5, random_state=123, shuffle=True) == 5
FAILED tests/test_settings.py::TestLoadConfig::test_treatment_config_multi - pydantic_core._pydantic_core.ValidationError: 1 validation error for AnalysisConfig
FAILED tests/test_settings.py::TestLoadConfig::test_mt_allows_dml - pydantic_core._pydantic_core.ValidationError: 1 validation error for AnalysisConfig
FAILED tests/test_tuning.py::TestOverfitPenaltyFormula::test_scale_invariant_r_loss - assert 0.06000000000000005 < 0.001
FAILED tests/test_tuning.py::TestOverfitPenaltyFormula::test_fmt_default_tolerance - assert -0.005 < -0.005
FAILED tests/test_tuning.py::TestCatBoostBootstrapFix::test_classifier_subsample_gets_mvs - AttributeError: module 'rubin.tuning' has no attribute '_build_catboost_classifier'
FAILED tests/test_tuning.py::TestCatBoostBootstrapFix::test_classifier_no_subsample_no_mvs - AttributeError: module 'rubin.tuning' has no attribute '_build_catboost_classifier'
FAILED tests/test_tuning.py::TestCatBoostBootstrapFix::test_classifier_explicit_bootstrap_preserved - AttributeError: module 'rubin.tuning' has no attribute '_build_catboost_classifier'
FAILED tests/test_tuning.py::TestCatBoostBootstrapFix::test_regressor_subsample_gets_mvs - AttributeError: module 'rubin.tuning' has no attribute '_build_catboost_regressor'
FAILED tests/test_tuning.py::TestCausalForestAdapterFromFitted::test_effect_delegates_to_cf - assert (2, 1) == (2,)
FAILED tests/test_tuning.py::TestBuildBaseLearner::test_both_without_learner_type_fallback - AttributeError: <module 'rubin.tuning' from '/mnt/rubin/rubin/tuning/__init__.py'> does not have the attribute '_build_catboost_classifier'
FAILED tests/test_uplift_metrics.py::TestPolicyValue::test_all_below_threshold - assert -0.005684204631366708 == 0.0
FAILED tests/test_uplift_metrics.py::TestPolicyValuePerArm::test_all_below_threshold - assert -0.25 == 0.0
FAILED tests/test_uplift_metrics.py::TestPolicyValuePerArm::test_arm2_ignores_arm1 - assert -0.02886726193670923 == -0.16774541531823087 ± 1.0e-10
=================================================================================================================================================================== 21 failed, 121 passed in 16.42s ===========================================================================================================================================================
